#pragma once
#include "sound.h"

#define SOUND_DISTANCE 50.0f

enum READ_SOUND
{
//BGM
	BGM_TITLE,
	BGM_CHARACTER,
	BGM_SELECT,
	BGM_GAME,
	BGM_RESULT_LOSE,
	BGM_RESULT_WIN,

//SE
	//Fade
	SE_SCENE_SHIFT,

	//Title & Select
	SE_BUTTON_1,
	SE_BUTTON_2,
	SE_SELECT_CHANGE,

	//Game
	//SE_HOVER,

	SE_PLAYER_ATTACK,
	SE_PLAYER_ATTACK_BLOCK,
	SE_PLAYER_DAMAGE,
	SE_PLAYER_LOW_HP,
	SE_PLAYER_SCREAM,
	SE_PLAYER_DEATH,
	SE_PLAYER_WALL_COLLISION,

	SE_STOP,
	SE_STOP_REVERSE,
	SE_SLOW,
	SE_SLOW_REVERSE,
	SE_COOLDOWN_FINISH,

	SE_EXPLOSION_SMALL,
	SE_EXPLOSION_MEDIUM,
	SE_EXPLOSION_BIG,

	SE_ENEMY_DAMAGE,
	SE_ENEMY_FOLLOW_SOUND,
	SE_ENEMY_BULLET_LAUNCH,
	SE_ENEMY_SUMMON_SPAWN,
	SE_ENEMY_SUMMON_SOUND,
	SE_ENEMY_SUMMON_DEATH,
	SE_ENEMY_SUMMONER_SOUND,
	SE_ENEMY_TICK,
	SE_ENEMY_DEATH,

	SE_ITEM_SPAWN,
	SE_ITEM_COLLECT_HP,
	SE_ITEM_COLLECT_XP,

	SE_LEVEL_UP,
	SE_PAUSE_IN,
	SE_PAUSE_OUT,
	SE_COUNTDOWN,

	//Result
	SE_WIN,
	SE_LOSE,

	//XXXXXXXXXXXX
	READ_SOUND_MAX,
	READ_SOUND_NONE
};

enum SOUND_TYPE
{
	SE,
	BGM
};

void ReadSound();
void SetVolumeForReadSound(READ_SOUND num, float volume);
void StopReadSound(READ_SOUND num);
void PlayReadSound(READ_SOUND num, SOUND_TYPE type);
void PlayReadSound(READ_SOUND num, SOUND_TYPE type, float volume);
